// src/components/MapDisplay.svelte
<script>


	import { selectedEntry } from '$lib/Database.js';
	import { invoke } from '@tauri-apps/api/tauri';


	$: selected = null;
	$: img = null;
	$: imgLoading = true;
	selectedEntry.subscribe(entry => {
		if (entry) {
			img = null;
			imgLoading = true;
			selected = entry;
			invoke('get_image', { mapId: selected.id }).then(imgReturn => {
				imgLoading = false;
				return img = imgReturn;
			});
		}
	});
</script>

{#if selected}
	<div>
		{#if !imgLoading}
			{#if img}
			<img alt='{`Preview screenshot for ${selected.title}`}' style='max-width: 100%'
					 src='data:image/jpeg;base64, {img}' />
				{:else}
				<p>No preview available</p>
				{/if }
		{:else }

			<i class='fa fa-pulse fa-spinner fa-3x' />

		{/if}
	</div>

	<div
		style="max-height: 20%; overflow-y: scroll;margin:5px 0 5px 0;background: whitesmoke">{@html (selected.description || "")}</div>
	<div id='action-buttons'>
		<button id='install-button' disabled class="btn btn-block">Install</button>

		<div class="input-group">
			<select id='map-select' class="form-select" disabled></select>
			<button class="btn input-group-btn" id='play' disabled>Play map</button>
		</div>
	</div>
{:else}
	<p>No map selected</p>
{/if}

// src/components/MapDisplay.jsx
import Contexts from '../lib/Contexts.ts';
import {useContext, useEffect, useState} from 'react';
import {Button} from "./spectre/Button.jsx";
import {invoke} from "@tauri-apps/api/tauri";
import {navigate} from "../lib/QuaddictedLink.js";

function MapDisplay() {

  const [img, setImg] = useState();
  const {selectedEntry} = useContext(Contexts.Database);
  const [imgLoading, setImgLoading] = useState(false);

  useEffect(() => {
    if (selectedEntry) {
      setImgLoading(true);
      invoke("get_image", {mapId: selectedEntry.id}).then(imgReturn => {
        setImgLoading(false);
        setImg(imgReturn);
      });
    }
  }, [selectedEntry]);

  if (selectedEntry) {
    return <div>
      <Button color="link" block={true} onClick={() => navigate(selectedEntry.id + ".html")}>{selectedEntry.title}</Button>
      {!imgLoading
        ? (
          img
            ? <img alt={`Preview image for ${selectedEntry.title}`} style={{width: "100%"}}
                   src={`data:image/jpeg;base64, ${img}`}/>
            : <p>No preview available</p>
        )
        : <i className="fa fa-spinner fa-pulse fa-3x"></i>
      }
      <p style={{maxHeight: "25vh", overflowY: "scroll", marginTop: '5px'}}
         dangerouslySetInnerHTML={{__html: selectedEntry.description}}/>

    </div>;
  } else {
    return <p>No map selected</p>;
  }
}

export default MapDisplay;
